/** Google Maps / Places (New) Table A business types, shown as searchable segments. */
export const GOOGLE_PLACE_SEGMENTS: { value: string; label: string }[] = [
  { value: 'accounting', label: 'Accounting / CA firms' },
  { value: 'airport', label: 'Airports' },
  { value: 'amusement_park', label: 'Amusement parks' },
  { value: 'aquarium', label: 'Aquariums' },
  { value: 'art_gallery', label: 'Art galleries' },
  { value: 'atm', label: 'ATMs' },
  { value: 'auto_parts_store', label: 'Auto parts stores' },
  { value: 'automobile_repair', label: 'Auto repair' },
  { value: 'bakery', label: 'Bakeries' },
  { value: 'bank', label: 'Banks' },
  { value: 'bar', label: 'Bars' },
  { value: 'barber_shop', label: 'Barber shops' },
  { value: 'beauty_salon', label: 'Beauty salons' },
  { value: 'bed_and_breakfast', label: 'Bed and breakfasts' },
  { value: 'bicycle_store', label: 'Bicycle stores' },
  { value: 'book_store', label: 'Book stores' },
  { value: 'bowling_alley', label: 'Bowling alleys' },
  { value: 'bus_station', label: 'Bus stations' },
  { value: 'cafe', label: 'Cafes' },
  { value: 'campground', label: 'Campgrounds' },
  { value: 'car_dealer', label: 'Car dealers' },
  { value: 'car_rental', label: 'Car rental' },
  { value: 'car_repair', label: 'Car repair' },
  { value: 'car_wash', label: 'Car wash' },
  { value: 'casino', label: 'Casinos' },
  { value: 'cell_phone_store', label: 'Mobile phone stores' },
  { value: 'cemetery', label: 'Cemeteries' },
  { value: 'child_care_agency', label: 'Child care' },
  { value: 'church', label: 'Churches' },
  { value: 'city_hall', label: 'City halls' },
  { value: 'clothing_store', label: 'Clothing stores' },
  { value: 'coffee_shop', label: 'Coffee shops' },
  { value: 'consultant', label: 'Consultants' },
  { value: 'convenience_store', label: 'Convenience stores' },
  { value: 'courier_service', label: 'Courier services' },
  { value: 'courthouse', label: 'Courthouses' },
  { value: 'dental_clinic', label: 'Dental clinics' },
  { value: 'dentist', label: 'Dentists' },
  { value: 'department_store', label: 'Department stores' },
  { value: 'doctor', label: 'Doctors' },
  { value: 'drugstore', label: 'Drugstores' },
  { value: 'electrician', label: 'Electricians' },
  { value: 'electronics_store', label: 'Electronics stores' },
  { value: 'embassy', label: 'Embassies' },
  { value: 'event_venue', label: 'Event venues' },
  { value: 'farm', label: 'Farms' },
  { value: 'fashion_store', label: 'Fashion stores' },
  { value: 'fast_food_restaurant', label: 'Fast food restaurants' },
  { value: 'fire_station', label: 'Fire stations' },
  { value: 'fitness_center', label: 'Fitness centers' },
  { value: 'florist', label: 'Florists' },
  { value: 'funeral_home', label: 'Funeral homes' },
  { value: 'furniture_store', label: 'Furniture stores' },
  { value: 'gas_station', label: 'Gas stations' },
  { value: 'gift_shop', label: 'Gift shops' },
  { value: 'golf_course', label: 'Golf courses' },
  { value: 'government_office', label: 'Government offices' },
  { value: 'grocery_store', label: 'Grocery stores' },
  { value: 'guest_house', label: 'Guest houses' },
  { value: 'gym', label: 'Gyms' },
  { value: 'hair_care', label: 'Hair salons' },
  { value: 'hair_salon', label: 'Hair salons' },
  { value: 'hardware_store', label: 'Hardware stores' },
  { value: 'hindu_temple', label: 'Hindu temples' },
  { value: 'home_goods_store', label: 'Home goods stores' },
  { value: 'hospital', label: 'Hospitals' },
  { value: 'hostel', label: 'Hostels' },
  { value: 'hotel', label: 'Hotels' },
  { value: 'ice_cream_shop', label: 'Ice cream shops' },
  { value: 'insurance_agency', label: 'Insurance agencies' },
  { value: 'interior_designer', label: 'Interior designers' },
  { value: 'jewelry_store', label: 'Jewelry stores' },
  { value: 'laundry', label: 'Laundries' },
  { value: 'lawyer', label: 'Law firms' },
  { value: 'library', label: 'Libraries' },
  { value: 'liquor_store', label: 'Liquor stores' },
  { value: 'local_government_office', label: 'Local government offices' },
  { value: 'locksmith', label: 'Locksmiths' },
  { value: 'lodging', label: 'Lodging' },
  { value: 'market', label: 'Markets' },
  { value: 'medical_lab', label: 'Diagnostic / medical labs' },
  { value: 'mosque', label: 'Mosques' },
  { value: 'motel', label: 'Motels' },
  { value: 'movie_theater', label: 'Movie theaters' },
  { value: 'moving_company', label: 'Moving companies' },
  { value: 'museum', label: 'Museums' },
  { value: 'night_club', label: 'Night clubs' },
  { value: 'optometrist', label: 'Optometrists' },
  { value: 'painter', label: 'Painters' },
  { value: 'park', label: 'Parks' },
  { value: 'parking', label: 'Parking' },
  { value: 'pet_store', label: 'Pet stores' },
  { value: 'pharmacy', label: 'Pharmacies' },
  { value: 'physiotherapist', label: 'Physiotherapists' },
  { value: 'plumber', label: 'Plumbers' },
  { value: 'police', label: 'Police stations' },
  { value: 'post_office', label: 'Post offices' },
  { value: 'primary_school', label: 'Primary schools' },
  { value: 'real_estate_agency', label: 'Real estate' },
  { value: 'restaurant', label: 'Restaurants' },
  { value: 'resort_hotel', label: 'Resorts' },
  { value: 'roofing_contractor', label: 'Roofing contractors' },
  { value: 'school', label: 'Schools' },
  { value: 'secondary_school', label: 'Secondary schools' },
  { value: 'shoe_store', label: 'Shoe stores' },
  { value: 'shopping_mall', label: 'Shopping malls' },
  { value: 'spa', label: 'Spas' },
  { value: 'sporting_goods_store', label: 'Sporting goods stores' },
  { value: 'stadium', label: 'Stadiums' },
  { value: 'storage', label: 'Warehouses / storage' },
  { value: 'store', label: 'Stores' },
  { value: 'supermarket', label: 'Supermarkets' },
  { value: 'synagogue', label: 'Synagogues' },
  { value: 'taxi_stand', label: 'Taxi stands' },
  { value: 'tourist_attraction', label: 'Tourist attractions' },
  { value: 'train_station', label: 'Train stations' },
  { value: 'travel_agency', label: 'Travel agencies' },
  { value: 'university', label: 'Universities / colleges' },
  { value: 'veterinary_care', label: 'Veterinary clinics' },
  { value: 'wholesaler', label: 'Wholesalers' },
  { value: 'zoo', label: 'Zoos' },
];

export function filterGooglePlaceSegments(query: string) {
  const q = query.trim().toLowerCase();
  if (!q) return GOOGLE_PLACE_SEGMENTS;
  return GOOGLE_PLACE_SEGMENTS.filter(
    (item) => item.label.toLowerCase().includes(q) || item.value.replace(/_/g, ' ').includes(q)
  );
}
